
===|Dev Logs :TSR_1556112883|===============================================

getpath invoked and returns :/home/automation/webapps/AutoBox/BDD/Core/../Logs/TSR_1556112883/Images/
FindElement invoked 
type invoked  :xpath



Find Element Failed :
Traceback (most recent call last):
  File "/home/automation/webapps/AutoBox/BDD/Core/SeleniumFunction.py", line 24, in FindElement
    element=driver.find_element_by_xpath(variable)
AttributeError: 'tuple' object has no attribute 'find_element_by_xpath'




FindElement invoked 
type invoked  :xpath



Find Element Failed :
Traceback (most recent call last):
  File "/home/automation/webapps/AutoBox/BDD/Core/SeleniumFunction.py", line 24, in FindElement
    element=driver.find_element_by_xpath(variable)
AttributeError: 'tuple' object has no attribute 'find_element_by_xpath'




FindElement invoked 
type invoked  :xpath



Find Element Failed :
Traceback (most recent call last):
  File "/home/automation/webapps/AutoBox/BDD/Core/SeleniumFunction.py", line 24, in FindElement
    element=driver.find_element_by_xpath(variable)
AttributeError: 'tuple' object has no attribute 'find_element_by_xpath'




FindElement invoked 
type invoked  :xpath



Find Element Failed :
Traceback (most recent call last):
  File "/home/automation/webapps/AutoBox/BDD/Core/SeleniumFunction.py", line 24, in FindElement
    element=driver.find_element_by_xpath(variable)
AttributeError: 'tuple' object has no attribute 'find_element_by_xpath'




FindElement invoked 
type invoked  :xpath



Find Element Failed :
Traceback (most recent call last):
  File "/home/automation/webapps/AutoBox/BDD/Core/SeleniumFunction.py", line 24, in FindElement
    element=driver.find_element_by_xpath(variable)
AttributeError: 'tuple' object has no attribute 'find_element_by_xpath'



